"""add job activity

Revision ID: 1c060b9ee10d
Revises: 0002_jobs
Create Date: 2026-09-04 10:47:18.076114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1c060b9ee10d'
down_revision: Union[str, Sequence[str], None] = '0002_jobs'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_activity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('created', 'status_changed', 'note', 'email', 'phone_call', 'interview', 'offer', 'rejection', 'other', name='job_activity_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_activity_created_at'), 'job_activity', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_activity_job_id'), 'job_activity', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_activity_type'), 'job_activity', ['type'], unique=False)
    op.create_index(op.f('ix_job_activity_user_id'), 'job_activity', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_activity_user_id'), table_name='job_activity')
    op.drop_index(op.f('ix_job_activity_type'), table_name='job_activity')
    op.drop_index(op.f('ix_job_activity_job_id'), table_name='job_activity')
    op.drop_index(op.f('ix_job_activity_created_at'), table_name='job_activity')
    op.drop_table('job_activity')
    # ### end Alembic commands ###
